### ISSUE TITLE
ROS2 eloquent

### ISSUE THREAD

**Issue by hannes56a** [ipa320/cob_perception_common#103]
Hi,
is there some plan to make thos project compatible to ROS2 eloquent?
Or do you have any recommendation for an other similar project for ROS2?

At least i just need the "cob_object_detection_msgs"

Thanks a lot!

Hannes

**Comment by ipa-rmb** [comment]
@fmessmer do you have plans? I guess, from our side there will not be immeadiate efforts, but in the long run it might happen. @ipa-foj do you know, whether a ROS2 version is already planned from our side?

Best,
Richard

**Comment by hannes56a** [comment]
Hi,
i build my own msg package with the messages i need now.
Thanks for the answer

**Comment by fmessmer** [comment]
not planning any ros2 release any time soon
obviously the issue is solved in some other way for now
