### ISSUE TITLE
create branch for catkinized groovy

### ISSUE THREAD

**Issue by mgruhler** [ipa320/cob_perception_common#13]
Please create a branch groovy_catkin/groovy_dev_catkin for me to send a pull-request from ipa-mig/cob_perception_common@827d0ff455c1669458a795393e3e26522ad26910

Please test and report any issues!

**Comment by ipa-goa** [comment]
Created groovy_catkin/groovy_dev_catkin from groovy_dev. Pull request not possible, branches are identical.

**Comment by mgruhler** [comment]
Branch now called groovy_dev_catkin. Pull-Request #14 opened.

Thanks @ipa-goa
