### ISSUE TITLE
cob 4 integration, extend cob_image_flip

### ISSUE THREAD

**Issue by ipa-rmb** [ipa320/cob_perception_common#18]
- specify reference ks
- switch between 90° and continuous mode
  with
- yaml
- dynamic reconfigure

**Comment by NadiaHG** [comment]
solved and tested on HW

**Comment by ipa-rmb** [comment]
All done with pending pull request. Dynamic reconfigure not included since not needed.

**Comment by floweisshardt** [comment]
reopened because PR not merged

**Comment by fmessmer** [comment]
I guess we can finally close this as #47 has been merged.
#48 was for hydro, but that can be considered a "dont-care"
