### ISSUE TITLE
remove dependency to cob_vision_utils and move package itself

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_perception_common#23]
there is only a depedency to GlobalDefines.h which can be substituted. All other sources in cob_vision_utils are not relevant for any other bringup package.

**Comment by ipa-rmb** [comment]
Jan confirmed that the package is needed by many other packages. He will have a look on this whether it has to be tidied up. He will also check that the hydro version can build.

**Comment by floweisshardt** [comment]
is building now in hydro, see http://cob-jenkins-server:8080/job/ipa-ci__prio_build/arch=amd64,label=prio_build,repository=cob_perception_common__hydro,ros_distro=hydro,ubuntu_distro=precise/638/console

**Comment by NadiaHG** [comment]
Solved
