### ISSUE TITLE
remove hardcoded cob3-3

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_perception_common#45]
in cob_image_flip there is still a hardcoded parameter `robot=cob3-3`. Please remove default and add this to a yaml file configuration which can be set for each robot in `cob_hardware_config`.

**Comment by fmessmer** [comment]
see [this line](https://github.com/ipa320/cob_perception_common/blob/indigo_dev/cob_image_flip/ros/src/kinect_image_flip.cpp#L95)

**Comment by ipa-rmb** [comment]
Robot dependencies completely removed with #47 and #48
