### ISSUE TITLE
Cob_People_Detection Display and Client not working

### ISSUE THREAD

**Issue by bachapk** [ipa320/cob_perception_common#62]
When first time I installed these cob_people packages, everything worked well. But due to some reason it is not working at all. When I run : roslaunch cob_people_detection people_detection.launch OR roslaunch cob_people_detection people_detection.launch using_nodelets:=true it shows nothing in the display window. The display window is like this: 
![screenshot from 2016-05-30 14 02 47](https://cloud.githubusercontent.com/assets/19236442/15641072/dd0d21d4-2670-11e6-80e1-16c2655288a3.png)
Please note that roslaunch openni_launch openni.launch depth_registration:=true working perfectly and loading drivers successfully. Also kinect is connected.
 Also when I write this command: rosrun cob_people_detection people_detection_client then it says No connection to server 'load_model_server'. 
![screenshot from 2016-05-30 14 03 37](https://cloud.githubusercontent.com/assets/19236442/15641086/ecad60f4-2670-11e6-9e58-3da8cd2e1e89.png)
 I am new. Please help what is wrong. My /home/bacha/catkin_ws/src/cob_people_perception/cob_people_detection/common/files/training_data folder is empty. 
Bacha

**Comment by ipa-rmb** [comment]
Wrong package for this question but it has been answered already in the right package cob_poeple_perception .
