### ISSUE TITLE
Package Installation too invasive

### ISSUE THREAD

**Issue by RoboEvangelist** [ipa320/cob_perception_common#63]
Folks,

I installed the package, but it overridden my NiTE1.x installations, and also changed the paths in my cmake_prefix_path environment variable. Now I cannot run my other packages, even after uninstalling the cob_\* package.
I wonder if there is a way to install the NiTE2 from this repository in a local way so that it does not affect the rest of the package in ROS? By this I mean no Make/CMakeList hacking required from the user point of view. Or at least give the option to the user to install it locally, or globally. I don't think it's that difficult to do that.

Other than that, the face detection is pretty cool!

Thanks,

**Comment by ipa-rmb** [comment]
Hi,

Thanks for raising this issue. Since this is not related to the cob_perception_common package I have moved the discussion to the right repository cob_people_perception: https://github.com/ipa320/cob_people_perception/issues/45 .
