### ISSUE TITLE
[Question] Why is PoseStamped used instead of Pose in Detection.msg? 

### ISSUE THREAD

**Issue by cagbal** [ipa320/cob_perception_common#96]
Why do we use geometry_msgs/PoseStamped instead of just geormetry_msgs/Pose inside Detection.msg? Is there a special reason that this message has 2 headers(1 in detection, 1 in detection/posestamped)? 

You can see the line below:
https://github.com/ipa320/cob_perception_common/blob/e55f4a95559b613383dafc5306d00fb5a6f5a667/cob_perception_msgs/msg/Detection.msg#L7

**Comment by fmessmer** [comment]
I don't know where it comes from....but I highly suggest to leave it this way, as this message is vastly used in various downstream nodes and a message change would likely break a lot of downstream functionality...

if you need one with only one header, then please create a new one in addition to Detection.msg

**Comment by cagbal** [comment]
Ok then I will close this.
